AdManager/Models/Zone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AdManager.Models
{
    public class Zone
    {
        public int ID { get; set; }
        [Display(Name = "Пользователь")]
        public string UserID { get; set; }
        public ApplicationUser User { get; set; }
        [Display(Name = "Веб-сайт")]
        public int WebsiteID { get; set; }
        public Website Website { get; set; }
        [Required]
        [Display(Name = "Название")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Ширина блока(px)")]
        public int AdPlacementWidth { get; set; }
        [Required]
        [Display(Name = "Высота блока(px)")]
        public int AdPlacementHeight { get; set; }
        public virtual ICollection<Click> Clicks { get; set; }
    }
}

AdManager/Controllers/WebsitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdManager.Models;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace AdManager.Controllers
{
    [Authorize(Roles = "ADMIN,PUBLISHER")]
    public class WebsitesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationUserManager _userManager;

        public WebsitesController()
        {
        }

        public WebsitesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Websites
        public async Task<ActionResult> Index()
        {
            var userID = User.Identity.GetUserId();
            var isAdmin = await UserManager.IsInRoleAsync(userID, "ADMIN");
            IQueryable<Website> websites = db.Websites;
            if (!isAdmin)
            {
                websites = websites.Where(w => w.UserID.Equals(userID));
            }
            websites = websites.Include(w => w.User);
            return View(await websites.ToListAsync());
        }

        // GET: Websites/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = await db.Websites.FindAsync(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            return View(website);
        }

        // GET: Websites/Create
        public ActionResult Create()
        {
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email");
            return View();
        }

        // POST: Websites/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Url,Name,ContactName,ContactEmail")] Website website)
        {
            if (ModelState.IsValid)
            {
                //var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                website.UserID = User.Identity.GetUserId();

                db.Websites.Add(website);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", website.UserID);
            return View(website);
        }

        // GET: Websites/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = await db.Websites.FindAsync(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", website.UserID);
            return View(website);
        }

        // POST: Websites/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Url,UserID,Name,ContactName,ContactEmail")] Website website)
        {
            if (ModelState.IsValid)
            {
                db.Entry(website).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //ViewBag.UserID = new SelectList(db.Users, "Id", "Email", website.UserID);
            return View(website);
        }

        // GET: Websites/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Website website = await db.Websites.FindAsync(id);
            if (website == null)
            {
                return HttpNotFound();
            }
            return View(website);
        }

        // POST: Websites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Website website = await db.Websites.FindAsync(id);
            db.Websites.Remove(website);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdManager/Controllers/ZonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AdManager.Models;
using Microsoft.AspNet.Identity;

namespace AdManager.Controllers
{
    [Authorize(Roles = "ADMIN,PUBLISHER")]
    public class ZonesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Zones
        public async Task<ActionResult> Index()
        {
            var userID = User.Identity.GetUserId();
            var isAdmin = User.IsInRole("ADMIN");
            IQueryable<Zone> zones = db.Zones;
            if (!isAdmin)
            {
                zones = zones.Where(z => z.UserID.Equals(userID));
            }
            zones = zones.Include(z => z.User).Include(z => z.Website);
            return View(await zones.ToListAsync());
        }

        // GET: Zones/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zone zone = await db.Zones.Include("Website").SingleAsync(z => z.ID == id);
            if (zone == null)
            {
                return HttpNotFound();
            }

            var clicks = db.Clicks
                .Where(c => c.ZoneID.Equals(zone.ID))
                .Include(c => c.Campaign)
                .OrderByDescending(c => c.CreateAt);

            ViewBag.clicksAmount = await clicks.CountAsync();

            ViewBag.clicksTotalRevenue = await clicks.GroupBy(c => c.Currency).Select(c => new ClickRevenueCurrency {
                Revenue = c.Sum(i => i.Revenue),
                Currency = c.Key,
            }).ToListAsync();

            zone.Clicks = await clicks.ToListAsync();

            return View(zone);
        }

        // GET: Zones/Create
        public ActionResult Create()
        {
            var userID = User.Identity.GetUserId();
            ViewBag.WebsiteID = new SelectList(db.Websites.Where(w => w.UserID.Equals(userID)).ToList(), "ID", "Name");
            return View();
        }

        // POST: Zones/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,WebsiteID,Name,AdPlacementWidth,AdPlacementHeight")] Zone zone)
        {
            if (ModelState.IsValid)
            {
                zone.UserID = User.Identity.GetUserId();

                db.Zones.Add(zone);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            var userID = User.Identity.GetUserId();
            ViewBag.WebsiteID = new SelectList(db.Websites.Where(w => w.UserID.Equals(userID)).ToList(), "ID", "Name");

            return View(zone);
        }

        // GET: Zones/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zone zone = await db.Zones.FindAsync(id);
            if (zone == null)
            {
                return HttpNotFound();
            }

            var userID = User.Identity.GetUserId();
            ViewBag.WebsiteID = new SelectList(db.Websites.Where(w => w.UserID.Equals(userID)).ToList(), "ID", "Name", zone.WebsiteID);

            return View(zone);
        }

        // POST: Zones/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,UserID,WebsiteID,Name,AdPlacementWidth,AdPlacementHeight")] Zone zone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(zone).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            var userID = User.Identity.GetUserId();
            ViewBag.WebsiteID = new SelectList(db.Websites.Where(w => w.UserID.Equals(userID)).ToList(), "ID", "Name", zone.WebsiteID);

            return View(zone);
        }

        // GET: Zones/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Zone zone = await db.Zones.Include("Website").SingleAsync(z => z.ID == id);
            if (zone == null)
            {
                return HttpNotFound();
            }
            return View(zone);
        }

        // POST: Zones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Zone zone = await db.Zones.FindAsync(id);
            db.Zones.Remove(zone);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AdManager/Views/Zones/Create.cshtml
@model AdManager.Models.Zone

@{
    ViewBag.Title = "Создание";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Создание</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Зона</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.WebsiteID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WebsiteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WebsiteID, "", new { @class = "text-danger" })
                @Html.ActionLink("Создать веб-сайт", "Create", "Websites")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdPlacementWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdPlacementWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdPlacementWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdPlacementHeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdPlacementHeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdPlacementHeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdManager/Views/Zones/Delete.cshtml
@model AdManager.Models.Zone

@{
    ViewBag.Title = "Удаление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить данную запись?</h3>
<div>
    <h4>Зона</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WebsiteID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdPlacementWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdPlacementWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdPlacementHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdPlacementHeight)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

AdManager/Views/Zones/Details.cshtml
@model AdManager.Models.Zone

@{
    ViewBag.Title = "Информация";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Информация</h2>

<div>
    <h4>Зона</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.WebsiteID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdPlacementWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdPlacementWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdPlacementHeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdPlacementHeight)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>
<hr/>

<h4>Переходы</h4>
<dl class="dl-horizontal">
    <dt>
        Всего переходов
    </dt>
    <dd>
        @ViewData["clicksAmount"]
    </dd>
    <dt>
        Общий заработок
    </dt>
    <dd>
        @foreach (var item in ViewBag.clicksTotalRevenue)
        {
            <span class="label label-primary">@item.Revenue @item.Currency</span>
        }
    </dd>
</dl>

<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            Кампания
        </th>
        <th>
            Цена
        </th>
        <th>
            Дата
        </th>
        <th>
            Баннер
        </th>
    </tr>
    @foreach (var item in Model.Clicks)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Campaign.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Revenue) @Html.DisplayFor(modelItem => item.Currency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateAt)
            </td>
            <td>
                <a href="@item.Campaign.BannerImageUrl" target="_blank">
                    Просмотреть банер
                </a>
            </td>
        </tr>
    }
</table>

AdManager/Views/Zones/Edit.cshtml
@model AdManager.Models.Zone

@{
    ViewBag.Title = " Изменение";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Изменение</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Зона</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.UserID)

    <div class="form-group">
        @Html.LabelFor(model => model.WebsiteID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("WebsiteID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.WebsiteID, "", new { @class = "text-danger" })
            @Html.ActionLink("Создать веб-сайт", "Create", "Websites")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AdPlacementWidth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AdPlacementWidth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AdPlacementWidth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AdPlacementHeight, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AdPlacementHeight, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AdPlacementHeight, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdManager/Views/Zones/Index.cshtml
@model IEnumerable<AdManager.Models.Zone>

@{
    ViewBag.Title = "Зоны";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Зоны</h2>

<p>
    @Html.ActionLink("Создать", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        @if (User.IsInRole("ADMIN"))
        {
            <th>
                @Html.DisplayNameFor(model => model.UserID)
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.WebsiteID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdPlacementWidth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdPlacementHeight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ID)
        </td>
        @if (User.IsInRole("ADMIN"))
    {
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
}
        <td>
            @Html.ActionLink(item.Website.Name, "Details", "Websites", new { id = item.WebsiteID }, new { })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdPlacementWidth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AdPlacementHeight)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Просмотреть", "Details", new { id = item.ID }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.ID })
        </td>
    </tr>
}

</table>